  
CREATE DATABASE IF NOT EXISTS TIME_TRACKER;

DROP TABLE IF EXISTS `AGENT_MASTER`;
DROP TABLE IF EXISTS `DAY_MASTER`;
DROP TABLE IF EXISTS `DAY_DETAIL`;
DROP TABLE IF EXISTS `CHROME_TEMP_MASTER`;
DROP TABLE IF EXISTS `CHROME_TEMP_DETAILS`;
DROP TABLE IF EXISTS `CHROME_EXCEPTION_DETAILS`;
DROP TABLE IF EXISTS `PRODUCTIVE_URLS`;
DROP TABLE IF EXISTS `USER_PRIVILEGES`;
DROP TABLE IF EXISTS `SHIFT_TIMINGS`;
DROP TABLE IF EXISTS `CHROME_IDLE_INTERVAL`;
DROP TABLE IF EXISTS `USER_DETAILS`;
DROP TABLE IF EXISTS `PROGRAM_TRANSACTION`;
DROP TABLE IF EXISTS `PROJECT_TRANSACTION`;
DROP TABLE IF EXISTS `SUB_PROJECT_RELATION`;
DROP TABLE IF EXISTS `SERVICE_DELIVERY_MANAGER_RELATION`;
DROP TABLE IF EXISTS `TEAM_MANAGER_RELATION`;
DROP TABLE IF EXISTS `TEAM_LEADER_SUPERVISOR_RELATION`;
DROP TABLE IF EXISTS `LOCATION`;
DROP TABLE IF EXISTS `TEAM_LEADER_SUPERVISOR_RELATION`;

 
CREATE TABLE `CHROME_IDLE_INTERVAL` (
  `INTERVAL_SECS` int(11) NOT NULL,
  PRIMARY KEY (`INTERVAL_SECS`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO CHROME_IDLE_INTERVAL VALUES(90);

CREATE TABLE `AGENT_MASTER` (
  `EMAIL_ID` varchar(50) NOT NULL,
  `AGENT_ID` INT NOT NULL,
  `AGENT_NAME` varchar(50) NOT NULL,
  `PROJECT_ID` INT NOT NULL,
  `PROJECT_NAME` varchar(50) NOT NULL,
  `SUB_PROJECT_ID` INT NOT NULL,
  `SUB_PROJECT_NAME` varchar(25) NOT NULL,
  `LOCATION_ID` varchar(25) NOT NULL,
  `ALLOCATION_START_DT` date NOT NULL,
  `ALLOCATION_END_DT` date NOT NULL,
  `BILLABLE` varchar(50) NOT NULL,
  `ON_OFF` varchar(50) NOT NULL,
  `HCM_SUPERVISOR_ID` INT NOT NULL,
  `HCM_SUPERVISOR_NAME` varchar(50) NOT NULL,
  `FIELD2` varchar(50) DEFAULT NULL,
  `FIELD3` varchar(50) DEFAULT NULL,
  `FIELD4` varchar(50) DEFAULT NULL,
  `FIELD5` varchar(50) DEFAULT NULL,
  `FIELD6` varchar(50) DEFAULT NULL,
  `FIELD7` datetime DEFAULT NULL,
  `FIELD8` datetime DEFAULT NULL,
  `FIELD9` date DEFAULT NULL,
  `FIELD10` date DEFAULT NULL,
  PRIMARY KEY (`EMAIL_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



CREATE TABLE `CHROME_TEMP_DETAILS` (
  `EMAIL_ID` varchar(50) NOT NULL,
  `FROM_TIME` datetime NOT NULL,
  `TO_TIME` datetime NOT NULL,
  `WEBSITE_USED` varchar(500),
  `ACTIVITY_CODE` INT NOT NULL
  
);
CREATE TABLE `DAY_DETAIL` (
 `DATE` date NOT NULL,
  `EMAIL_ID` varchar(50) NOT NULL,
 `SNO` INT NOT NULL,
  `FROM_TIME` datetime NOT NULL,
  `TO_TIME` datetime NOT NULL,
  `WEBSITE_USED` varchar(500),
  `ACTIVITY_CODE` INT NOT NULL,
  PRIMARY KEY (`DATE`,`EMAIL_ID`,`SNO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `DAY_MASTER` (
  `DATE` date NOT NULL,
  `EMAIL_ID` varchar(50) NOT NULL,
  `AGENT_ID` INT NOT NULL,
  `AGENT_NAME` varchar(50) NOT NULL,
  `LOGIN_TIME` datetime NOT NULL,
  `LOGOUT_TIME` datetime NOT NULL,
  `PROD` float ,
  `IDLE` float ,
  `BREAK` float ,
  `MEALS` float,
  `HUDDLE` float ,
  `WELLNESS_SUPPORT` float ,
  `COACHING` float,
  `TEAM_MEETING` float ,
  `FB_TRAINING` float ,
  `NON_FB_TRAINING` float,
  `SHIFT_DETAILS` varchar(50) NOT NULL,
  `PROJECT_ID` INT NOT NULL,
  `PROJECT_NAME` varchar(50) NOT NULL,
  `SUB_PROJECT_ID` INT NOT NULL,
  `SUB_PROJECT_NAME` varchar(25) NOT NULL,
  `LOCATION_ID` varchar(25) NOT NULL,
  `BILLABLE` varchar(50) NOT NULL,
  `ON_OFF` varchar(50) NOT NULL,
  `HCM_SUPERVISOR_ID` INT NOT NULL,
  `HCM_SUPERVISOR_NAME` varchar(50) NOT NULL,
  `FIELD2` varchar(50) ,
  `FIELD3` varchar(50) ,
  `FIELD4` varchar(50),
  `FIELD5` varchar(50) ,
  `FIELD6` varchar(50) ,
  `FIELD7` datetime ,
  `FIELD8` datetime ,
  `FIELD9` date ,
  `FIELD10` date ,  
  PRIMARY KEY (`DATE`,`EMAIL_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `SHIFT_TIMINGS` (
  `PROJECT_ID` INT NOT NULL,
  `SUB_PROJECT_ID` INT NOT NULL,
    `LOCATION_ID` varchar(50) NOT NULL,
     `SNO` INT NOT NULL,
  `SHIFT_FROM` TIME NOT NULL,
  `SHIFT_TO` TIME NOT NULL,
 
  PRIMARY KEY (`PROJECT_ID`,`SUB_PROJECT_ID`,   `LOCATION_ID`, `SNO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
 

CREATE TABLE `CHROME_EXCEPTION_DETAILS` (
  `EMAIL_ID` varchar(50) NOT NULL,
  `FROM_TIME` datetime NOT NULL,
  `TO_TIME` datetime NOT NULL,
  `WEBSITE_USED` varchar(500) ,
  `ACTIVITY_CODE` INT NOT NULL,
   `ERROR_DESC` varchar(100) 
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `PRODUCTIVE_URLS` (
  `PROD_URL_ID` INT  NOT NULL,
  `PROD_URL_DETAILS` varchar(50)  NOT NULL,
  `MANAGER_ID` varchar(50)  NOT NULL,
  `MANAGER_NAME` varchar(50)  NOT NULL,  
  `REMARKS` varchar(50)  NOT NULL,
  `UPDATED_TIME` DATETIME  NOT NULL,
  `FIELD1` varchar(50)   ,
  `FIELD2` varchar(50)   ,
  `FIELD3` varchar(50)   ,
  `FIELD4` varchar(50)   ,
  `FIELD5` varchar(50)   ,
  `FIELD6` varchar(50)   ,
  `FIELD7` datetime   ,
  `FIELD8` datetime   ,
  `FIELD9` date   ,
  `FIELD10` date                   
);  


CREATE TABLE `USER_PRIVILEGES` (
  `USER_TYPE` varchar(20) NOT NULL,
  `PRIVILEGES_ID` int NOT NULL AUTO_INCREMENT,
  `VIEW_ONLY` varchar(5) NOT NULL,
  `PDF_EXPORT` varchar(5) NOT NULL,
  `CSV_EXPORT` varchar(5) NOT NULL,
  `EXCEL_EXPORT` varchar(5) NOT NULL,
  `PRINT` varchar(5) NOT NULL,
  `SINGLE_PROGRAM`varchar(5) NOT NULL,
  `MULTIPLE_PROGRAM`varchar(5) NOT NULL,
  `GLOBAL_PROGRAM`varchar(5) NOT NULL,
  `PROJECT`varchar(5) NOT NULL,
  `SUB_PROJECT`varchar(5) NOT NULL,
  `ADD_USER`varchar(5) NOT NULL,
  `EDIT_USER`varchar(5) NOT NULL,
  `DELETE_USER`varchar(5) NOT NULL,
  `FIELD1` varchar(5)   ,
  `FIELD2` varchar(5)   ,
  `FIELD3` varchar(5),
   PRIMARY KEY (`PRIVILEGES_ID`)
);

 CREATE TABLE `USER_DETAILS` (
  `USER_ID` INT NOT NULL,
  `USER_NAME` varchar(50) NOT NULL,
  `PASSWORD` varchar(70) NOT NULL,
  `PRIVILEGES_ID` int NOT NULL,
  `LOCATION_ID` varchar(30) NOT NULL,
  `STATUS` varchar(10) NOT NULL,
  `PASSWORD_FAILURE_COUNT` INT,
  `DESIGNATION` varchar(50),
  `PROGRAM_ID` varchar(50),
  `PROJECT_ID` varchar(50),
  `SUB_PROJECT_ID` varchar(50),
  `LAST_ACCESSED_TIME` DATETIME,
  `FIELD1` varchar(5)   ,
  `FIELD2` varchar(5)   ,
  `FIELD3` varchar(5),
   PRIMARY KEY (`USER_ID`)
);
  CREATE TABLE `PROGRAM_TRANSACTION` (
  `PROGRAM_ID` INT NOT NULL,
   `PROGRAM_NAME` varchar(50) NOT NULL,
   `PROGRAM_DESC` varchar(50) NOT NULL,
   `PROGRAM_MANAGER_ID` INT NOT NULL,
   `PROGRAM_MANAGER_NAME` varchar(50) NOT NULL,
   `PROJECT_ID` INT NOT NULL,
  `FIELD1` varchar(5)   ,
  `FIELD2` varchar(5)   ,
  `FIELD3` varchar(5),
   PRIMARY KEY (`PROGRAM_ID`,`PROJECT_ID`)
);
 
 
   CREATE TABLE `PROJECT_TRANSACTION` (
  `PROJECT_ID` INT NOT NULL,
  `PROJECT_NAME` varchar(50) NOT NULL,
  `PROJECT_MANAGER_ID` INT NOT NULL,
  `PROJECT_MANAGER_NAME` varchar(50) NOT NULL,
  `PROJECT_DESC` varchar(70) NOT NULL,
  `FIELD1` varchar(5)   ,
  `FIELD2` varchar(5)   ,
  `FIELD3` varchar(5),
   PRIMARY KEY (`PROJECT_ID`)
);

   CREATE TABLE `SUB_PROJECT_RELATION` (
  `PROJECT_ID` INT NOT NULL,
  `SUB_PROJECT_ID` INT NOT NULL,
  `SUB_PROJECT_NAME` varchar(30) NOT NULL,
  `LOCATION_ID` varchar(30) NOT NULL,
  `FIELD1` varchar(5)   ,
  `FIELD2` varchar(5)   ,
  `FIELD3` varchar(5),
   PRIMARY KEY (  `PROJECT_ID`,`SUB_PROJECT_ID`,  `LOCATION_ID`)
);
 
  CREATE TABLE `SERVICE_DELIVERY_MANAGER_RELATION` (
  `SUB_PROJECT_ID` INT NOT NULL,
  `LOCATION_ID` varchar(30) NOT NULL,
  `SNO` INT,
  `SENIOR_DELIVERY_MANAGER_ID` INT NOT NULL,
  `SENIOR_DELIVERY_MANAGER_NAME` varchar(50) NOT NULL,
  `FIELD1` varchar(5)   ,
  `FIELD2` varchar(5)   ,
  `FIELD3` varchar(5),
   PRIMARY KEY (  `SUB_PROJECT_ID` ,`LOCATION_ID`,  `SNO`)
);


 CREATE TABLE `TEAM_MANAGER_RELATION` (
  `SUB_PROJECT_ID` INT NOT NULL,
  `LOCATION_ID` varchar(30) NOT NULL,
   `SENIOR_DELIVERY_MANAGER_ID` INT NOT NULL,
  `SNO` INT,
 `TEAM_MANAGER_ID` INT NOT NULL,
  `TEAM_MANAGER_NAME` varchar(50) NOT NULL,
  `FIELD1` varchar(5)   ,
  `FIELD2` varchar(5)   ,
  `FIELD3` varchar(5),
   PRIMARY KEY (  `SUB_PROJECT_ID` ,`LOCATION_ID`, `SENIOR_DELIVERY_MANAGER_ID`, `SNO`)
);
  CREATE TABLE `TEAM_LEADER_SUPERVISOR_RELATION` (
  `SUB_PROJECT_ID` INT NOT NULL,
    `LOCATION_ID` varchar(30) NOT NULL,

  `SENIOR_DELIVERY_MANAGER_ID` INT NOT NULL,
  	  `SNO` INT,
 `TEAM_LEAD__SUPERVISOR_ID` INT NOT NULL,
  `TEAM_LEAD__SUPERVISOR_NAME` varchar(50) NOT NULL,
  `FIELD1` varchar(5)   ,
  `FIELD2` varchar(5)   ,
  `FIELD3` varchar(5),
   PRIMARY KEY (  `SUB_PROJECT_ID` ,`LOCATION_ID`, `SENIOR_DELIVERY_MANAGER_ID`, `SNO`)
);


   CREATE TABLE `LOCATION` (
  `LOCATION_ID` varchar(50) NOT NULL,
  `LOCATION_NAME` varchar(50) NOT NULL,
 
   PRIMARY KEY (  `LOCATION_ID`)
);
INSERT INTO `USER_PRIVILEGES`(`USER_TYPE`,`VIEW_ONLY`,`PDF_EXPORT`,`CSV_EXPORT`,`EXCEL_EXPORT`,`PRINT`,`SINGLE_PROGRAM`,`MULTIPLE_PROGRAM`,
`GLOBAL_PROGRAM`,`PROJECT`,`SUB_PROJECT`,`ADD_USER`,`EDIT_USER`,`DELETE_USER`)
VALUES('Admin','Yes','Yes','Yes','Yes','Yes','Yes','Yes','Yes','Yes','Yes','Yes','Yes','Yes');

INSERT INTO `USER_PRIVILEGES`(`USER_TYPE`,`VIEW_ONLY`,`PDF_EXPORT`,`CSV_EXPORT`,`EXCEL_EXPORT`,`PRINT`,`SINGLE_PROGRAM`,`MULTIPLE_PROGRAM`,
`GLOBAL_PROGRAM`,`PROJECT`,`SUB_PROJECT`,`ADD_USER`,`EDIT_USER`,`DELETE_USER`)
VALUES('Client','Yes','Yes','Yes','Yes','Yes','Yes','Yes','Yes','Yes','Yes','No','No','No');

INSERT INTO `USER_PRIVILEGES`(`USER_TYPE`,`VIEW_ONLY`,`PDF_EXPORT`,`CSV_EXPORT`,`EXCEL_EXPORT`,`PRINT`,`SINGLE_PROGRAM`,`MULTIPLE_PROGRAM`,
`GLOBAL_PROGRAM`,`PROJECT`,`SUB_PROJECT`,`ADD_USER`,`EDIT_USER`,`DELETE_USER`)
VALUES('Guest','Yes','No','No','No','No','Yes','Yes','Yes','Yes','Yes','No','No','No');


INSERT INTO `USER_PRIVILEGES`(`USER_TYPE`,`VIEW_ONLY`,`PDF_EXPORT`,`CSV_EXPORT`,`EXCEL_EXPORT`,`PRINT`,`SINGLE_PROGRAM`,`MULTIPLE_PROGRAM`,
`GLOBAL_PROGRAM`,`PROJECT`,`SUB_PROJECT`,`ADD_USER`,`EDIT_USER`,`DELETE_USER`)
VALUES('Super Business User','Yes','Yes','Yes','Yes','Yes','Yes','Yes','Yes','Yes','Yes','No','No','No');

INSERT INTO `USER_PRIVILEGES`(`USER_TYPE`,`VIEW_ONLY`,`PDF_EXPORT`,`CSV_EXPORT`,`EXCEL_EXPORT`,`PRINT`,`SINGLE_PROGRAM`,`MULTIPLE_PROGRAM`,
`GLOBAL_PROGRAM`,`PROJECT`,`SUB_PROJECT`,`ADD_USER`,`EDIT_USER`,`DELETE_USER`)
VALUES('Business User','Yes','Yes','Yes','Yes','Yes','Yes','Yes','Yes','Yes','Yes','Yes','Yes','Yes');

INSERT INTO `USER_PRIVILEGES`(`USER_TYPE`,`VIEW_ONLY`,`PDF_EXPORT`,`CSV_EXPORT`,`EXCEL_EXPORT`,`PRINT`,`SINGLE_PROGRAM`,`MULTIPLE_PROGRAM`,
`GLOBAL_PROGRAM`,`PROJECT`,`SUB_PROJECT`,`ADD_USER`,`EDIT_USER`,`DELETE_USER`)
VALUES('Program User','Yes','Yes','Yes','Yes','Yes','Yes','Yes','No','Yes','Yes','No','No','No');

INSERT INTO `USER_PRIVILEGES`(`USER_TYPE`,`VIEW_ONLY`,`PDF_EXPORT`,`CSV_EXPORT`,`EXCEL_EXPORT`,`PRINT`,`SINGLE_PROGRAM`,`MULTIPLE_PROGRAM`,
`GLOBAL_PROGRAM`,`PROJECT`,`SUB_PROJECT`,`ADD_USER`,`EDIT_USER`,`DELETE_USER`)
VALUES('Program Manager','Yes','Yes','Yes','Yes','Yes','Yes','No','No','Yes','Yes','No','No','No');


INSERT INTO `USER_PRIVILEGES`(`USER_TYPE`,`VIEW_ONLY`,`PDF_EXPORT`,`CSV_EXPORT`,`EXCEL_EXPORT`,`PRINT`,`SINGLE_PROGRAM`,`MULTIPLE_PROGRAM`,
`GLOBAL_PROGRAM`,`PROJECT`,`SUB_PROJECT`,`ADD_USER`,`EDIT_USER`,`DELETE_USER`)
VALUES('Project Manager','Yes','Yes','Yes','Yes','Yes','No','No','No','Yes','Yes','No','No','No');


INSERT INTO `USER_PRIVILEGES`(`USER_TYPE`,`VIEW_ONLY`,`PDF_EXPORT`,`CSV_EXPORT`,`EXCEL_EXPORT`,`PRINT`,`SINGLE_PROGRAM`,`MULTIPLE_PROGRAM`,
`GLOBAL_PROGRAM`,`PROJECT`,`SUB_PROJECT`,`ADD_USER`,`EDIT_USER`,`DELETE_USER`)
VALUES('Team Lead','No','No','No','No','No','No','No','No','No','Yes','No','No','No');

INSERT INTO `USER_PRIVILEGES`(`USER_TYPE`,`VIEW_ONLY`,`PDF_EXPORT`,`CSV_EXPORT`,`EXCEL_EXPORT`,`PRINT`,`SINGLE_PROGRAM`,`MULTIPLE_PROGRAM`,
`GLOBAL_PROGRAM`,`PROJECT`,`SUB_PROJECT`,`ADD_USER`,`EDIT_USER`,`DELETE_USER`)
VALUES('Supervisor','No','No','No','No','No','No','No','No','No','Yes','No','No','No');




CREATE INDEX INDEX_DAY_MASTER
ON DAY_MASTER (EMAIL_ID);
CREATE INDEX INDEX_DAY_DETAIL
ON DAY_DETAIL (EMAIL_ID);